sudo: required
language: python
services:
- docker
script:
- sudo docker run -ti --rm --workdir /var/src -v $(pwd):/var/src denis4inet/build-keeweb
  bash -c "npm install; grunt mobile"
deploy:
  provider: releases
  api_key:
    secure: ${ENCRYPTED_GITHUB_KEY}
  file: "./cordova/platforms/android/build/outputs/apk/android-debug.apk"
  on:
    repo: denis4net/keeweb
